### ISSUE TITLE
Leverage GeoArrow to speedup vector data processing & viz

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/global-hydrography#1]
The [Apache Arrow](https://arrow.apache.org/) language-independent columnar memory format improves computational and I/O performance so substantially that Pandas 2.0 (and many other libraries) are adopting arrow for the data backend. [Pyarrow will be a required dependency of Pandas 3.0](https://pandas.pydata.org/pdeps/0010-required-pyarrow-dependency.html), which will use arrow over numpy by default.

This [arrow revolution](https://datapythonista.me/blog/pandas-20-and-the-arrow-revolution-part-i) is now extending to geospatial encodings with the creation of [GeoArrow](https://geoarrow.org) as an alternative to `wkt` and `wkb` (Well Known Text/Binary) for geospatial vector data. The new geospatial visualization library, [lonboard](https://developmentseed.org/lonboard/latest/), leverages GeoArrow and [GeoParquet](https://geoparquet.org/) to [substantially speedup and scale up vector data visualization](https://developmentseed.org/blog/2024-03-29-new-in-lonboard).

[GDAL v3.9](https://github.com/OSGeo/gdal/blob/v3.9.0/NEWS.md) released on May 10, 2024 added "read/write support for GeoArrow (struct-based) encoding (GeoParquet 1.1)". [pyogrio v0.8.0](https://github.com/geopandas/pyogrio/releases/tag/v0.8.0) released May 6, 2024 introduced "writing based on Arrow as the transfer mechanism of the data from Python to GDAL" and "`read_arrow` and `open_arrow` now provide [GeoArrow-compliant extension metadata](https://geoarrow.org/extension-types.html), including the CRS."  

The fact that pyogrio only recently enabled full support for arrow and explains why my tests of using the arrow engine in April didn't yet show expected speedups.

The full benefits of GeoArrow are not quite yet available to the entire geospatial python ecosystem. [geoarrow-python](https://github.com/geoarrow/geoarrow-python) does not yet have a release to take advantage of the latest GDAL and pyogrio releases (but the main branch does with[ PR#49](https://github.com/geoarrow/geoarrow-python/pull/49)) and the latest [rasterio 1.3.10](https://github.com/rasterio/rasterio/releases/tag/1.3.10) is packaged to prevent conda from installing GDAL 3.9 into the environment.

So so we either need to wait a few weeks or months to fully benefit from GeoArrow or we need to install pre-release versions of geoarrow-python and rasterio (as shown here https://github.com/geoarrow/geoarrow-python?tab=readme-ov-file#installation).

Either way, we want to move toward using GeoArrow as soon as possible, as I suspect it will substantially improve our ability to simplify, dissolve, and visualize geometries for our global rivers and their basins.

cc: @kieranbartels, @ptomasula, @rajadain

**Comment by rajadain** [comment]
Thanks a lot @aufdenkampe for this write up! It has really helped me put the pieces together for how many of these technologies fit together.

I read into [how Lonboard works](https://developmentseed.org/lonboard/latest/how-it-works/), and it uses Deck.GL at the browser level.

ModelMW uses Leaflet, and it is quite heavily entrenched in the project. Upgrading that to MapLibre or Deck.GL would be a significant effort.

Given that, I don't think we can quite use the GeoArrow + GeoParquet solution for visualizations in ModelMW. However, it is still a good candidate for analysis.

For visualization, our best bet will likely be to generate Vector Tiles and serve them via S3. Leaflet has support for them via the [VectorGrid plugin](https://github.com/Leaflet/Leaflet.VectorGrid), and can visualize large amounts of data in a much more efficient manner than GeoJSON.

I'll try to create a demo using some of the streams / basins to show what it looks like, we'll have a better sense then.

---

One of the drawbacks of this approach is storage: we end up with two copies of the dataset, one in Vector Tiles, another in GeoParquet.

Apparently it is technically possible to read data from Vector Tiles for analysis, using libraries such as [mapbox-vector-tile](https://github.com/tilezen/mapbox-vector-tile) and shapely, which would allow us to use one dataset instead of two, but I'm not sure what the runtime performance would be like. Will have to make a couple experiments to see.

**Comment by aufdenkampe** [comment]
## Read Method Performance

These results depend on using [GDAL v3.9](https://github.com/OSGeo/gdal/blob/v3.9.0/NEWS.md) and a dev version of [geoarrow-python](https://github.com/geoarrow/geoarrow-python). For the tests below, our updated environment (6552d34) installed:
  ```yml
  - gdal  =3.9.0
  - pyogrio =0.8.0
  - pyarrow =16.1.0
  - geopandas =0.14.4
  - geoarrow-pyarrow =0.1.3.dev4 # installed from head of dev branch via github
  ``` 
Our previous environment, using gdal-3.8.5 and earlier versions of the above was 2-3x slower!

Benchmarks from commit 06e2d6d based on reading all fields in the 702.3 MB 'TDX_streamnet_7020038340_01.gpkg' file.

| Function                   | engine  | use_arrow | geoarrow | time             | relative |
|----------------------------|---------|-----------|----------|------------------|---------:|
| `pyogrio.read_arrow()`     | NA      | NA        | No       | 535 ms ± 12.9 ms | 1.0      |
| `pyogrio.read_dataframe()` | NA      | True      | No       | 2.24 s ± 18.8 ms | 4.2      |
| `pyogrio.read_dataframe()` | NA      | False     | No       | 8.54 s ± 4.94 s  | 16.0     |
| `gpd.read_file()`          | pyogrio | True      | No       | 1.97 s ± 10.5 ms | 3.7      |
| `gpd.read_file()`          | pyogrio | False     | No       | 3.06 s ± 29.1 ms | 5.7      |
| `gpd.read_file()`          | fiona | False     | No       | 50.3 s ± 1.34 s  | 94.0     |
| `pyogrio.read_arrow()`     | NA      | NA        | Yes      | 552 ms ± 18.2 ms | 1.0      |
| `pyogrio.read_dataframe()` | NA      | True      | Yes      | 13.7 s ± 391 ms  | 25.6     |
| `gpd.read_file()`          | pyogrio | True      | Yes      | 14.1 s ± 1.11 s  | 26.4     |


`pyogrio.read_arrow()` is ~4x faster than the fastest alternative method.

`gpd.read_file(fp, engine='pyogrio', use_arrow=True)` is the 2nd fastest method, but only before importing GeoArrow.

`gpd.read_file()` is the slowest method, 94x slower than `pyogrio.read_arrow()` and 16x slower than adding `engine='pyogrio', use_arrow=True` arguments!

Importing GeoArrow massively slows down `pyogrio.read_dataframe()` and `gpd.read_file()`. Read speeds for `pyogrio.read_arrow()` do not change.

NOTE:
- `pyogrio.read_dataframe(use_arrow=True)` took 5-8 seconds (2-3 times slower!) when running a previous environment with gdal-3.8.5. **It is critical to use the specified environment!**

### Recommendations

- Use `gpd.read_file(fp, engine='pyogrio', use_arrow=True)` for data pre-processing workflows that use Pandas/GeoPandas functions for data frames.
- Explore use of `pyogrio.read_arrow()` or `geoarrow.pyarrow.io.read_pyogrio_table()` for production workflows that keep everything as pyarrow tables.

**Comment by aufdenkampe** [comment]
I demonstrated some that **reading only what you need** further speeds reads in the latest `examples/3_GenerateModifiedNestedSetIndex.ipynb` (presently in the `processing` branch).

For the 186.78 MB 'TDX_streamnet_7020038340_01_mnsi.parquet' with 140,097 reaches, saved with `zstd` compression but no partioning (i.e. row chunking).

Reference:
```py
gpd.read_parquet(path)
# 2.98 s ± 68 ms
```

## Read Only Non-Geometry Columns for 250x speedup!!!
```py
pd.read_parquet(path, columns=non_geom)` 
# 11.8 ms ± 481 µs
```
NOTE: It is necessary to use the Pandas method, because [`geopandas.read_parquet()`](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_parquet.html) will throw an error if no geometry field is read.

## Read only selected Rows for 2x speedup!
Read 4897 rows (out of 140097 total) where 'ROOT_ID'==750288662
```py
gpd.read_parquet(path, filters=[('ROOT_ID', '==', 750288662)] 
# 1.57 s ± 35.7 ms
```
NOTE: This uses `**kwargs` in [`geopandas.read_parquet()`](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_parquet.html) that are passed to [`pyarrow.parquet.read_table()`](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html#pyarrow.parquet.read_table).

Partioning, or row chunking, the GeoParquet when we write it would increase read speeds further.

**Comment by aufdenkampe** [comment]
Closing this issue as we have fully explored and documented speedups that are possible with the current library versions released this summer. 

Further speedups will clearly be enabled in the future! We'll explore them then.
