### ISSUE TITLE
Asynchronously Pulling NGA Data

### ISSUE THREAD

**Issue by kieranbartels** [WikiWatershed/global-hydrography#2]
The [NGA ](https://earth-info.nga.mil/) website has 124 files on their Geosciences tab that we are trying to download. These files range from 1 GB to 9GB. We want to asynchronously pull this data via a script.

**Comment by kieranbartels** [comment]
An asynchronous main function was created in io.py. To run this script run `python ./src/global_hydrography/io.py` in the terminal. The asynchronous aspect is working properly, but about 50% of the time the data downloads will fail because of the below error:

```
Failed to download https://earth-info.nga.mil/php/download.php?file=1020011530-streamnet-gpkg: Response payload is not completed: <ContentLengthError: 400, message='Not enough data for satisfy content length header.'>. ConnectionResetError(22, 'The specified network name is no longer available', None, 64, None)
```

One potential solution is retry the download when it fails, but there is not a 100% chance the data download will work the 2nd or 3rd time around. 

I also tried another async method based on this [article ](https://hackernoon.com/how-to-speed-up-file-downloads-with-python), which is currently the second half of io.py that is commented out. This method did not work either because of a similar header which turned into a permissions error.

```
  File "C:\Users\kbartels\AppData\Local\miniconda3\envs\hydrography\Lib\site-packages\aiohttp\client_proto.py", line 94, in connection_lost
    uncompleted = self._parser.feed_eof()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 510, in aiohttp._http_parser.HttpParser.feed_eof
    raise ContentLengthError(
aiohttp.http_exceptions.ContentLengthError: 400, message:
  Not enough data for satisfy content length header.

```

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\kbartels\\OneDrive - LimnoTech\\GitHub\\global-hydrography\\download.phpduwn8p7o\\download.php.part0'
```

**Comment by ptomasula** [comment]
@kieranbartels and @aufdenkampe, I looked into the error that Kieran noted above. I made sure that we are setting an explicit no timeout but still arrived at the same error. 

Digging into the call stack of the error I get the output below. My interpretation is that the connection is being closed on the host's end (i.e. the NGA service is closing the connection, not us). 

`
await self._wait("read")\n  File "c:\\Users\\ptomasula\\AppData\\Local\\miniconda3\\envs\\hydrography\\Lib\\site-packages\\aiohttp\\streams.py", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <ContentLengthError: 400, message=\'Not enough data for satisfy content length header.\'>. ConnectionResetError(10054, \'An existing connection was forcibly closed by the remote host\', None, 10054, None)\n'
`

Getting around that may prove a trickier that if if the connection issues were on our end. I have a few idea though: 
1. We could try limiting the number of connection we make with the client fsspec is using (I believe the default is 100). This should let us throttle our requests as little, but my testing also resulted in an error with 4 datasets. This doesn't bode well for a high degree of concurrency. 
2. We could implement a reliability queue, where failed download attempts are pushed to the back of the queue and attempted again once a download worker has availability. This would let us try again on errors, but we probably want some cutoff after x max attempts. 
4. We could also switch back to a synchronous approach, though with 64 large datasets that's a bit of a lost for throughput.

**Comment by ptomasula** [comment]
I've been playing around with option 1 of the above (... try limiting the number of connection...) and it seems like 2 is the limit where I'm not getting the host to close the connection. That might just be our speed limit here. We aren't going to be able to control the host, so short of some sort of clustering approach, so our traffic is coming from multiple clients, I'm not sure I have a fix for async performance.

**Comment by aufdenkampe** [comment]
@ptomasula, thanks for digging into this and finding that it still works for 2 at a time. 

Let's move move forward with this approach, on a modeling computer, ASAP. Can you help @kieranbartels get started (i.e. select the right modeling computer, etc.) to make that happen?

**Comment by aufdenkampe** [comment]
This work was completed between June 6-18, including a confirmation check with commit 8c3f1081a3d11ac97f91df26614f049e9325d469 that all downloaded files were the same size as original files.

My understanding is that this was done by running the following files from a command line:
- Download: `src/global_hydrography/io.py`
- Check files: `src/global_hydrography/check_files.py`

@kieranbartels, can you confirm and share the commands in a comment here for documentation.
