### ISSUE TITLE
Implement Modified Nest Set Index for Rapid Watershed Delineation

### ISSUE THREAD

**Issue by ptomasula** [WikiWatershed/global-hydrography#3]
# Summary
The paper [Development of a data model to facilitate rapid watershed delineation](https://doi.org/10.1016/j.envsoft.2017.06.009) proposes a graph algorithm based approach for watershed delineation using a modified nested set index. The outlined approach would allow selection of upstream reaches from a given node (reach) based on two numerical indices, in place of more conventional techniques like adjacency lists or binary search. 

# Closure Criteria 
- [x] Implement a modified nested set indexing algorithm to generate index for TDX hydro stream net geopackage files
- [x] Provide documentation on how to utilize output from nest set index for delineation
- [x] Run instructions for generating the modified nested set index from source files.

**Comment by ptomasula** [comment]
Thanks @aufdenkampe for connecting and helping debug this issue. As noted in the commit message for [
b21c352](https://github.com/WikiWatershed/global-hydrography/commit/b21c35206394cb1c6df45201ed704417863e0a54), the previous implementation's conversion from a GeoDataFrame into a dictionary and back again was resulting in the loss of critical type information (e.g. CRS). As a result, the write method was not able to function correctly. The example notebook should be working now.

**Comment by aufdenkampe** [comment]
The final revisions to `examples/3_GenerateModifiedNestedSetIndex.ipynb` with commit cb245a08bef4ac5f07137d5157619dfe7eb06185 closes this issue by providing the `create_tdx_mnsi()` function that provides a performance and storage optimized approach that:
- Opens an original streamnet GeoPackage file
- Creates a Modified Nested Set Index fields, 
- Converts all LINKNO-related fields to globally unique values
- Drops useless fields that are not functionally populated with values
- Sets LINKNO as the index for to facilitate selection and interoperability with the basins datasets
- Saves a compressed streamnet GeoParquet file that is 26% of the size (~4x smaller) than the original GeoPackage file
