### ISSUE TITLE
Dissolving Logic for Upstream Watershed Boundary Given LINKNO/streamID   

### ISSUE THREAD

**Issue by ptomasula** [WikiWatershed/global-hydrography#7]
# Summary
With the modified nest set index now implemented (MSNI) (see #3), the next step is to develop logic to utilize the MSNI to rapidly delineate a watershed polygon given the LINKNO/streamID for a reach. Some of the logic for how to utilize the MNSI is provided in this [section of the README](https://github.com/WikiWatershed/global-hydrography/blob/main/README.md#modified-nested-set-index) file. 

The task for this issue is to develop the delineation logic and return a single polygon representing the upstream watershed of a provided reach id (LINKNO/streamID)

# Closure Criteria
- [ ] Function developed for subsetting the network based on modified nest set index
- [ ] Function to combining (dissolving) subset of basins into a single polygon
- [ ] Tests developed to verify resultant polygon matches known result
- [ ] Performance of logic has been tested and characterized

**Comment by ptomasula** [comment]
In exploring performance for some of the dissolve logic, it seems likely that we will need to implement some sort of pre-dissolve layer to maintain an acceptable level of performance for larger watersheds. I'll open a new issue to for the development of that logic, though I do provide a draft implementation in [0ab4609](https://github.com/WikiWatershed/global-hydrography/commit/0ab46093b8eaa975eb6f263498f42c2a6a33464d).

**Comment by aufdenkampe** [comment]
Over the last month, we've demonstrated with [`examples/5_DelineateWatershed.ipynb`](https://github.com/WikiWatershed/global-hydrography/blob/main/examples/5_DelineateWatershed.ipynb) that the pre-dissolve logic works very well. 

For example, it nicely divides the Delaware River Basin into 25 basins (when using a 200 basin threshold) that are a little smaller than USGS HUC-08:

![image](https://github.com/user-attachments/assets/8f4f693a-a785-40c8-99dd-292f38d25cb8) 

We then used the [Geopandas `gdf.dissolve()`](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.dissolve.html), which is a geospatial groupby function that applies "the [`union_all()`](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.union_all.html) method to all geometries" within each dissolve group. We found an **18.5x speedup** when using the `method="coverage"` option, which optimized for non-overlapping polygons such as those found in the full resolution TDX Hydro basins files. I confirmed that this is appropriate for our dataset as it does not produce any invalid geometries. See https://github.com/WikiWatershed/global-hydrography/issues/8#issuecomment-2430409251.

This logic is ready for primetime!
